-- Optional demo objects for manual experiments.
-- The real checker does not require this file.

CREATE SCHEMA IF NOT EXISTS pgcollcheck_demo;

CREATE TABLE IF NOT EXISTS pgcollcheck_demo.sample_strings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    nickname text NOT NULL,
    code text COLLATE "C" NOT NULL
);

INSERT INTO pgcollcheck_demo.sample_strings (name, nickname, code)
VALUES
    ('Ёлка', 'elka', 'A001'),
    ('Ель', 'yel', 'A002'),
    ('ångström', 'angstrom', 'A003'),
    ('apple', 'Apple', 'A004'),
    ('Äpfel', 'apfel', 'A005')
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS sample_strings_name_idx
    ON pgcollcheck_demo.sample_strings (name);

CREATE INDEX IF NOT EXISTS sample_strings_code_c_idx
    ON pgcollcheck_demo.sample_strings (code COLLATE "C");
